const ORDER_STATUS = {
  PENDING: 'PENDING',
  UTR_SUBMITTED: 'UTR_SUBMITTED',
  PAYMENT_UNDER_REVIEW: 'PAYMENT_UNDER_REVIEW',
  RECONCILED: 'RECONCILED',
  DISPUTED: 'DISPUTED',
  EXPIRED: 'EXPIRED',
  CANCELLED_BY_BUYER: 'CANCELLED_BY_BUYER',
};

const BUCKET_STATUS = {
  ACTIVE: 'ACTIVE',
  FULL: 'FULL',
  PAUSED: 'PAUSED',
  CLOSED: 'CLOSED',
};

const LEDGER_STATUS = {
  OPEN: 'OPEN',
  PARTIAL: 'PARTIAL',
  SETTLED: 'SETTLED',
  OVERPAID: 'OVERPAID',
};

const CONFIRM_ACTION = {
  RECONCILE: 'RECONCILE',
  DISPUTE: 'DISPUTE',
};

module.exports = {
  ORDER_STATUS,
  BUCKET_STATUS,
  LEDGER_STATUS,
  CONFIRM_ACTION,
};
